#!/bin/bash

HR=\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#
NEWLINE="
"

APP="css/app.css"
BOOTSTRAP="css/vendor/bootstrap.css"
BOOTSTRAP_RESPONSIVE="css/vendor/bootstrap-responsive.css"
FONTAWESOME="css/vendor/font-awesome.css"
LESS="less"
STYLE="css/style.css"
STYLE_MIN="css/style.min.css"
STYLE_LESS="less/style.less"

echo "$NEWLINE"
echo "$HR"
echo "# Watching Application"
echo "$HR"
echo "$NEWLINE"

echo "Watching $STYLE"
recess $STYLE_LESS:$STYLE --watch $LESS &

echo "Watching $APP"
nwatch --file $STYLE_MIN --run "recess $STYLE $FONTAWESOME $BOOTSTRAP_RESPONSIVE $BOOTSTRAP --compress > $APP" &