#!/bin/bash

HR=\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#
NEWLINE="
"

APP="./css/app.css"
BOOTSTRAP="./css/vendor/bootstrap.css"
BOOTSTRAP_RESPONSIVE="./css/vendor/bootstrap-responsive.css"
FONTAWESOME="./css/vendor/font-awesome.css"
STYLE="./css/style.css"
STYLE_MIN="./css/style.min.css"
STYLE_LESS="./less/style.less"

echo "$NEWLINE"
echo "$HR"
echo "# Building Application"
echo "$HR"
echo "$NEWLINE"

echo "Compiling $STYLE_LESS to $STYLE"
recess $STYLE_LESS --compile > $STYLE

echo "Compiling application CSS to $APP";
recess $STYLE $FONTAWESOME $BOOTSTRAP_RESPONSIVE $BOOTSTRAP --compress > $APP